# Site settings
title: PHP Versions
email: mjftrask@gmail.com
description: >
  Learn which versions of PHP are available on different web hosting providers, so you can make informed decisions.
baseurl: "" # the subpath of your site, e.g. /blog/
keywords: "php, versions, hosts, shared hosts, managed hosts, paas, hosting platforms, php versions"
url: "http://phpversions.info" # the base hostname & protocol for your site
twitter_username: phpversions
# github_username:  jekyll

# Build settings
markdown: kramdown

permalink: pretty

exclude: [bin, vendor, php-vendor]
